# Setup
title:        Engineering @ VIANT
company:      VIANT
pagename:     Viant Open Source Page
tagline:      A Place to Show the World What We Can Do
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Viant Data Engineering Team
  url:        http://viant.github.io 
  email:      ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
